name: flutter_speed_dial
description: Flutter plugin to implement a beautiful and dynamic Material Design Speed Dial, with labels, animated icons and hide on scrolling.
version: 3.0.5
homepage: https://github.com/darioielardi/flutter_speed_dial/

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

flutter:
