name: flutter_speed_dial
description: Flutter plugin to implement a beautiful and dynamic Material Design Speed Dial with labels, animated icons, multi-directional children and much more.
version: 6.1.0+1
homepage: https://github.com/darioielardi/flutter_speed_dial/

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

flutter:
